### ISSUE TITLE
I have submitted my app Review it

### ISSUE THREAD

**Issue by Robokishan** [masakifukunishi/pwa-list#30]
Name: Pomodoro for notion database
website: https://pomodoro.kishanjoshi.dev/

**Comment by masakifukunishi** [comment]
What does this issue mean?

**Comment by Robokishan** [comment]
I have submitted project in the pwa list app it is showing currently under review

**Comment by masakifukunishi** [comment]
Thank you :)
 I'll check your app later

**Comment by masakifukunishi** [comment]
I checked your app and changed to public.
But you don't need to make an issue when you submit.
Thank you 🎉
